articles:
    - content/articles/**/*.md

ci-cd:
    - .github/**/*.yml

dependencies:
    - ./**/requirements.txt
    - requirements*.txt

géocapot:
    - content/internal/**/*

mkdocs:
    - content/**/*.pages
    - mkdocs*.yml

rdp:
    - content/rdp/**/*.md

thème:
    - content/theme/**/*
