version: '3.7'

services:
  website:
    container_name: geotribu-contribuer-site
    image: geotribu-contribuer-mkdocs
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIT_PYTHON_REFRESH=warn
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: mkdocs serve --config-file mkdocs-minimal.yml --dirtyreload --dev-addr=0.0.0.0:8000
