icon:
  repo: fontawesome/brands/github-alt
  tag:
    default: fontawesome/solid/tag
    # -- custom tags icons
    ananas: material/fruit-pineapple
    atlas: fontawesome/solid/book-atlas
    balai: material/broom
    brick: material/toy-brick
    cerveau: material/brain
    citrouille: material/pumpkin
    code: fontawesome/solid/code
    commentaires: fontawesome/solid/comments
    conference: fontawesome/solid/person-chalkboard
    database: fontawesome/solid/database
    drone: material/drone
    facebook: fontawesome/brands/facebook
    feuille: fontawesome/solid/leaf
    geoloupe: fontawesome/solid/magnifying-glass-location
    git: fontawesome/brands/git-alt
    globe: fontawesome/solid/earth-europe
    google: fontawesome/brands/google
    html: fontawesome/brands/html5
    institution: fontawesome/solid/building-columns
    js: fontawesome/brands/js
    manette: fontawesome/solid/gamepad
    markdown: fontawesome/brands/markdown
    masques: fontawesome/solid/masks-theater
    meridiens: fontawesome/solid/globe
    moteur: material/engine
    oeuf: fontawesome/solid/egg
    open: fontawesome/solid/lock-open
    opensource: material/open-source-initiative
    pingouin: simple/linux
    python: fontawesome/brands/python
    roue: material/cog-play
    route: fontawesome/solid/route
    rstats: fontawesome/brands/r-project
    satellite: fontawesome/solid/satellite-dish
    streetview: fontawesome/solid/street-view
    tente: material/tent
    telephone: material/cellphone-marker
    ubuntu: material/ubuntu
    wikipedia: material/wikipedia
    windows: fontawesome/brands/windows
